= JS/Alt
Rahul Somasunderam
:toc: left
:source-highlighter: highlightjs
:icons: font

In talking to a lot of Javascript developers over the course of the last few months, I learnt that most hated the limits placed on them by javascript.
I found myself cursing every time I needed to do some very basic tasks.
Most of this led back to a rather old decision to not use transpilers when we started our very first SPA.
This project is an attempt to find out what we could be doing instead of fighting hard against javascript.

== The problems

* Javascript pretends to be a functional language
* Javascript pretends to be an object oriented language
* Javascript was introduced in 1995, and has never broken backwards compatibility.
    _Even when bad decisions were made._
* Javascript has [line-through]#optional# **no** typing.

== The use cases

. Calling utility methods that accept functions as arguments
. Creating "class"es and accessing static and instance methods
. Dealing with some javascript eccentricities
. Managing types

== The format

You'll see code that is picked from tested examples over here.
There will be callouts that point out interesting things.
Some are positive, some are negative, while others are just plain interesting.

== The Contenders

=== Classic Javascript (ES 5)

[source,javascript]
----
include::../assets/app/TaylorClassic.js[]
----
<1> This is a tip of the hat to the weird history of javascript and the reluctance to do away with bad implementations.
As we'll later see, this is not as strict as we want it to be.
<2> This is a secret handshake between the developer and the browser that **this** is a `class`.
<3> This is the constructor, and it does nothing, but it can be modified in several steps below.
<4> The `prototype` feels like you're mucking with a meta object. Indeed, that's how javascript wants you to deal with
classes.
<5> As you've probably noticed by now, there are no types to parameters or return values.
Javascript does not impose any restrictions inspite of having classes we've seen earlier.
The solution to getting type information in the IDE is use of JSDoc.
You might be tempted to think there is Haskell style type inference.
Do not fall for that trap. Things can go from bad to worse pretty soon once a method is called incorrectly.
<6> There is no sane definition of `this` since classes are just functions.
So what `this` means depends on where it is used. In this case, it's an instance of `FactorialUtilClassic`.
An experienced javascript developer would know this by instinct, but still fall for it's traps.
<7> Here we're using lodash or underscore or some library that offers a functional style of programming.
<8> This is the boilerplate required to call reduce
<9> If you forget the `return` keyword, the function is assumed to return `void`. There is no warning.
<10> This is a static function. The clue is, there's no `prototype`.
<11> `this` means the `class` over here.
<12> We return the function from <3> over here. That is the instance returned to the call `new FactorialUtilClassic`.

[source,javascript]
----
include::../assets/app/TaylorClassic.spec.js[]
----

=== Modern Javascript (ES 6)

[source,js]
----
include::../assets/app/TaylorModern.es6[]
----
<1> There is native support for classes.
<2> Arrow functions look a lot like Lambda Calculus, and have a saner implementation of `this`
<3> There is support for `static` members in classes.
<4> You still use `this` inside static members.

[source,js]
----
include::../assets/app/TaylorModern.spec.js[]
----

=== Coffeescript

[source,coffeescript]
----
include::../assets/app/TaylorCoffee.coffee[]
----
<1> This is based on ES5, so you still need to enforce strict mode
<2> It is based on Ruby and Python so indents matter and comments are `#` based
<3> You have native classes
<4> This is a function defined as a property, which in case of class is a public method
<5> It is not immediately clear in this case, but if is not a statement, but an expression in coffeescript.
<6> `@` is used to mapped to `this` or `this.` in javascript. Makes for concise code more than you would think.
<7> There is still a lambda-esque function here, but coffeescript functions always remind you of lambdas.
<8> The last statement is always a return
<9> Depending on the implementation of Coffeescript, the whole function could be inside of an anonymous function or not.
So if you want to export the class, you better explicitly do that.

[source,coffeescript]
----
include::../assets/app/TaylorCoffee.spec.coffee[]
----
The test is perhaps where coffeescript excels in demonstrating it's conciseness.

=== Grooscript
[source,groovy]
----
include::../main/groovy/jsalt/groovy/TaylorGroovy.groovy[]
----
<1> Within Groovy code, you can use Static compilation and type checking
<2> You can have typed variables
<3> Typed functions
<4> There is no `this` scattered in a confusing way. But the implementation of `this` is as sane as `groovy`.
<5> Some ASTs like `@Singleton` are not allowed

[source,groovy]
----
include::../test/groovy/jsalt/groovy/TaylorGroovySpec.groovy[]
----
<1> We are using Spock to test the code
<2> The assertions are much nicer than jasmine
<3> Jasmine's `toBeCloseTo` is missed

=== scala.js
[source,scala]
----
include::../main/scala/TaylorScala.scala[]
----
<1> `if` is an expression, not a statement.
<2> Also function bodies without `{}` are common.
<3> Since we're using recursion, we need to be very clear about the signature inspite of advanced type inference.
<4> This is a method body with `{}`.
<5> Also Scala infers the return of this method. It is not `Object`.
<6> ScalaJs is very aggressive in optimizing generated javascript. We need to tell it what we will be using from
  outside unless we have a `JSApp` with a `main` method.
<7> More demo of advanced type inference.

[source,scala]
----
include::../test/scala/TaylorScalaSpec.scala[]
----
<1> This is commented because it is implicit, but I've put it there to show by default scala collections are immutable.
<2> We need this because we're trying to play well with the other test written in Spock.
<3> Assertions are almost as elegant as Spock.

=== Purescript
[source,haskell]
----
include::../main/purescript/TaylorPurescript.purs[]
----
<1> This line is commented out, but conventionally it would be there. It demonstrates Purescript's type inference.
  Purely on the basis of the operations performed inside of it, it will guess exactly the same type as I had intended.
<2> This is a function defined using guard values
<3> This is a function defined using pattern matching
<4> This appears necessary for the module to be taken seriously by the compiler
<5> The commented block is better performing code. It uses tail call optimization. If you need it, you should use it.
  TCO is almost a must-have if you want to use quickcheck

[source,haskell]
----
include::../test/purescript/TaylorPurescriptTest.purs[]
----
<1> This defines a property for quickCheck
<2> This is *quickCheck* - it runs a hundred tests with random numbers to see if the property holds true
<3> You need ot put negative numbers into parens. It's a _haskell_ thing.

However purescript doesn't generate JUnit style xml output. So we've gone ahead and put in some jasmine tests as well

[source,javascript]
----
include::../assets/app/TaylorPurescript.spec.js[]
----
<1> This is how you pull in Purescript into native javascript. There is the option to use CommonJS or whatever else
  is your favorite module system for JS, but we're keeping it simple.
<2> This is where you blame your favorite mathematician - Gottlob Frege, Moses Schönfinkel, or Haskell Curry.
  It is what makes sens to mathematics. And it's ugly when we take a programming language where Currying is not a first
  class capability.

=== Clojurescript
TODO

=== Typescript
[source,typescript]
----
include::../assets/app/TaylorTypescript.ts[]
----
<1> This is how we tell typescript where to import things
<2> Typing is optional. There is no int, so everything is a number.
<3> Lodash chaining does not work. It's a flaw in the `d.ts` for it.
<4> The insane littering of `this` doesn't go away.

[source,typescript]
----
include::../assets/app/TaylorTypescript.spec.ts[]
----